export default function TermsPage() {
  return (
    <main className="max-w-3xl mx-auto px-6 py-12 text-foreground">
      <h1 className="text-3xl font-semibold mb-2">Preci – Terms of Use</h1>
      <p className="text-sm text-gray-500 mb-8">
        Last updated: 31 March 2026
      </p>

      <Section title="1. Introduction">
        <p>
          Preci ("we", "us", "our") provides an AI-powered service that helps
          users better understand consumer contracts by generating
          plain-language summaries. Preci is designed to support informed
          decision-making and <strong>does not provide legal advice</strong>.
        </p>
        <p className="mt-3">
          By accessing or using Preci, you agree to these Terms of Use. If you
          do not agree, please do not use the service.
        </p>
      </Section>

      <Section title="2. Nature of the Service (Important)">
        <ul className="list-disc ml-6 space-y-2">
          <li>Are generated by artificial intelligence</li>
          <li>May not capture every detail of a contract</li>
          <li>Are not a substitute for legal advice</li>
        </ul>
        <p className="mt-3">
          You remain fully responsible for any decision you make based on a
          contract.
        </p>
      </Section>

      <Section title="3. No Legal Advice Disclaimer">
        <p>
          Preci is <strong>not a law firm</strong> and does not provide legal
          advice. Nothing on the platform should be relied upon as legal advice.
        </p>
      </Section>

      <Section title="4. User Responsibilities">
        <ul className="list-disc ml-6 space-y-2">
          <li>You have the right to upload your documents</li>
          <li>You will not upload unauthorized content</li>
          <li>You will not use Preci unlawfully</li>
        </ul>
      </Section>

      <Section title="5. Accuracy and Limitations">
        <ul className="list-disc ml-6 space-y-2">
          <li>AI outputs may contain inaccuracies</li>
          <li>No guarantee of completeness or correctness</li>
        </ul>
      </Section>

      <Section title="6. Payments and Access">
        <ul className="list-disc ml-6 space-y-2">
          <li>Prices are shown before payment</li>
          <li>Payments handled by third parties</li>
          <li>Access granted after payment</li>
        </ul>
      </Section>

      <Section title="7. Intellectual Property">
        <p>
          You retain ownership of your documents. Preci only processes them to
          provide the service.
        </p>
      </Section>

      <Section title="8. Suspension or Termination">
        <p>
          We may suspend or terminate access if the service is misused or these
          Terms are violated.
        </p>
      </Section>

      <Section title="9. Limitation of Liability">
        <p>
          Preci is not liable for losses resulting from reliance on summaries.
        </p>
      </Section>

      <Section title="10. Governing Law">
        <p>These Terms are governed by South African law.</p>
      </Section>
    </main>
  );
}

function Section({ title, children }) {
  return (
    <section className="mb-8">
      <h2 className="text-lg font-semibold mb-2">{title}</h2>
      <div className="text-sm leading-relaxed space-y-2">{children}</div>
    </section>
  );
}